ARG ROS_DISTRO
FROM ros:${ROS_DISTRO}

ARG USER=ros
ARG GROUP=ros
ARG USER_ID=1000
ARG GROUP_ID=1000

# local colcon workspace folder for ros-user
ARG COLCON_WS=/home/${USER}/ws

RUN groupadd -g ${GROUP_ID} ${GROUP}
RUN useradd -ms /bin/bash -u ${USER_ID} -g ${GROUP_ID} ${USER}

RUN apt-get update &&\
  apt-get install -y \
    wget gpg &&\
  apt-get clean &&\
  rm -rf /var/lib/apt/lists/*

# install latest gazebo garden release
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg &&\
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null &&\
  apt-get update &&\
  apt-get install -y gz-garden &&\
  apt-get clean &&\
  rm -rf /var/lib/apt/lists/*


# install turtlebot description and navigation packages
RUN apt-get update &&\
  apt-get install \
    ros-${ROS_DISTRO}-ros2launch \
    ros-${ROS_DISTRO}-turtlebot3-navigation2 \
    ros-${ROS_DISTRO}-turtlebot3-cartographer \
    ros-${ROS_DISTRO}-turtlebot3-msgs \
    ros-${ROS_DISTRO}-turtlebot3-description \
    ros-${ROS_DISTRO}-imu-sensor-broadcaster \
    ros-${ROS_DISTRO}-diff-drive-controller \
    ros-${ROS_DISTRO}-effort-controllers \
    ros-${ROS_DISTRO}-joint-state-broadcaster \
    ros-${ROS_DISTRO}-ros2controlcli \
    ros-${ROS_DISTRO}-controller-manager \
    ros-${ROS_DISTRO}-velocity-controllers \
    ros-${ROS_DISTRO}-xacro \
    ros-${ROS_DISTRO}-joint-trajectory-controller \
    ros-${ROS_DISTRO}-rviz2 \
    ros-${ROS_DISTRO}-tricycle-controller \
    ros-${ROS_DISTRO}-gps-msgs \
    ros-${ROS_DISTRO}-hls-lfcd-lds-driver \
    -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# We don't need sound
RUN echo "pcm.!default = null;" > /etc/asound.conf

COPY ./entrypoint.sh /ros2_ws_entrypoint.sh
RUN chmod a+x /ros2_ws_entrypoint.sh
ENTRYPOINT [ "/ros2_ws_entrypoint.sh" ]

RUN mkdir -p ${COLCON_WS}/log \
    && chown -R ${USER_ID}:${GROUP_ID} ${COLCON_WS}/

# Workaround to overwrite GraphicsMagick / not getting segfault on nav2
# see https://github.com/ros-planning/navigation2/issues/2109 for details
COPY GraphicsMagick-1.3.37 /opt/GraphicsMagick-1.3.37
RUN cd /opt/GraphicsMagick-1.3.37 && ./configure && make && make install

USER ros
WORKDIR /home/${USER}/

# this uses the latest fork from https://github.com/ros-controls/gz_ros2_control/pull/67
RUN cd ${COLCON_WS}/ \
    && git clone https://github.com/ros-controls/gz_ros2_control.git -b ahcorde/rename/ign_to_gz \
    && git clone https://github.com/gazebosim/ros_gz.git -b ros2 \
    && git clone https://github.com/gazebosim/gz-transport.git -b gz-transport12
    # && git clone https://github.com/gazebosim/gz-math.git -b gz-math7
    # && rosdep update \
    # && rosdep install --from-paths ./ -i -y --rosdistro ${ROS_DISTRO}

# get some coffee - building the packages takes around 20 minutes
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
  cd ${COLCON_WS}/ && \
  colcon build

COPY ./turtlebot3_simulations ${COLCON_WS}/turtlebot3_simulations
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
  cd ${COLCON_WS}/ && \
  colcon build

# CMD gz sim
CMD ros2 launch turtlebot3_gz gz_sim.launch.py
